We noticed multiple CI errors over the last week, e.g. https://gitlab.com/veloren/veloren/-/jobs/4749826609
$ if [[ ! "${SCHEDULE_CADENCE}" =~ ${TAG_REGEX} ]]; then # collapsed multi-line command
warning: redirecting to https://gitlab.com/veloren/veloren.git/
Locking support detected on remote "origin". Consider enabling it with:
  $ git config lfs.https://veloren-bot:[MASKED]@gitlab.com/veloren/veloren.git/info/lfs.locksverify true
ref weekly:: Error in git rev-list --stdin --objects --not --remotes=origin --: exit status 128 fatal: bad object 11bc48033cf4e6528268f2acd97324e16e118bce
error: failed to push some refs to 'https://veloren-bot:[MASKED]@gitlab.com/veloren/veloren'

There seems to be a fix proposed here: https://github.com/git-lfs/git-lfs/issues/3977 by running git fetch first.
lets try it out. Maybe we need to give it some commandline parameters to optimize in the future